language: node_js
node_js:
  - '6.3.1'
cache:
  directories:
    - node_modules
before_install:
  - chmod +x ./bin/deploy
  - chmod +x ./bin/build
  - chmod +x ./bin/add-ssh-key
  - ./bin/add-ssh-key
script:
  - ./bin/deploy
